# Generated by Django 5.2.3 on 2025-06-29 08:24

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fidelidad', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('beneficio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidadLimite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=20)),
                ('sigla', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8)),
                ('idcategoria_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriacliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEmp', models.CharField(max_length=50)),
                ('apeEmp', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8)),
                ('numeroTelefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precioporPorcion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='extras/')),
                ('idcategoria_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaextra')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unidadmedida')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMesa', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=30)),
                ('idmozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadTotalPlatos', models.IntegerField()),
                ('cantidadTotalBebidas', models.IntegerField()),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('idmesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoPagado', models.DecimalField(decimal_places=2, max_digits=8)),
                ('montoRestante', models.DecimalField(decimal_places=2, max_digits=8)),
                ('montoTotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
                ('metodo', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='BebidaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precioFinal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('id_bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bebida')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('personalizable', models.BooleanField(default=False)),
                ('idcategoria_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaplato')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraPlato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadPorciones', models.IntegerField()),
                ('id_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extra')),
                ('id_plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plato')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precioBasePlato', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precioFinalPlato', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipoPedido', models.CharField(max_length=50)),
                ('idpedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
                ('idplato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plato')),
            ],
        ),
        migrations.CreateModel(
            name='ExtrasPlatoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precioPersonalizacion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idextra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extra')),
                ('idplato_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.platopedido')),
            ],
        ),
        migrations.AddField(
            model_name='bebida',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unidadmedida'),
        ),
        migrations.CreateModel(
            name='StockBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.almacen')),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bebida')),
            ],
            options={
                'unique_together': {('bebida', 'almacen')},
            },
        ),
        migrations.CreateModel(
            name='StockComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.almacen')),
                ('extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extra')),
            ],
            options={
                'unique_together': {('extra', 'almacen')},
            },
        ),
    ]
