# Generated by Django 5.2.3 on 2025-07-13 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platopedido',
            name='idpedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos', to='api.pedido'),
        ),
    ]
