# Generated by Django 5.2.3 on 2025-07-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='idmesa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.mesa'),
        ),
        migrations.AlterField(
            model_name='platopedido',
            name='tipoPedido',
            field=models.CharField(default='Para servir', max_length=50),
        ),
    ]
