# Generated by Django 5.2.3 on 2025-06-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='extras/'),
        ),
    ]
