# Generated by Django 5.2 on 2025-07-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bebida',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='bebidas/'),
        ),
        migrations.AddField(
            model_name='plato',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='platos/'),
        ),
    ]
