# Generated by Django 5.2.3 on 2025-07-09 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bebida_imagen_plato_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='metodo',
        ),
    ]
