# Generated by Django 5.2.3 on 2025-06-21 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_almacen_area_unidadmedida_extra_unidad_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.almacen'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='extra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.extra'),
        ),
    ]
