# Generated by Django 5.2.3 on 2025-07-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pedido_estado_alter_pedido_idmesa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platopedido',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
