# Generated by Django 5.2.3 on 2025-06-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stock_almacen_alter_stock_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra',
            name='cantidad_Disponible',
        ),
        migrations.AddField(
            model_name='bebida',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.unidadmedida'),
        ),
    ]
