# Generated by Django 5.2.3 on 2025-07-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pago_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('Billetera Virtual', 'Billetera Virtual'), ('Tarjeta', 'Tarjeta'), ('Efectivo', 'Efectivo')], default='Efectivo', max_length=50),
        ),
    ]
