# Generated by Django 5.2.3 on 2025-07-14 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_platopedido_idpedido'),
        ('api', '0003_platopedido_cantidad'),
    ]

    operations = [
    ]
