# Generated by Django 5.2.3 on 2025-06-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_extra_cantidad_disponible_bebida_unidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='StockComida',
        ),
        migrations.CreateModel(
            name='StockBebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveBigIntegerField(default=0)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.almacen')),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bebida')),
            ],
            options={
                'unique_together': {('bebida', 'almacen')},
            },
        ),
    ]
