# Generated by Django 5.2.3 on 2025-06-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_stock_stockcomida_stockbebida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
